name: Node CI

permissions:
  contents: read

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: npm
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          npx playwright install chromium
          npm test
        env:
          CI: true
