name: Node CI

permissions:
  contents: read

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: npm
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          npx playwright install chromium
          npm test
        env:
          CI: true
